repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: flake8
        language_version: python3
        args: [--ignore=E731 W503, --per-file-ignores=tests/*:F401, --max-line-length=100, --max-complexity=10,]
